-- Lina Line CMS additions
alter table public.site_settings add column if not exists ceo_name text default 'Paulina Oti';
alter table public.site_settings add column if not exists ceo_bio text default 'Founder and creative leader of Lina Line Fashion Hub & Academy.';
alter table public.site_settings add column if not exists ceo_image text;
create table if not exists public.fashion_categories (id bigint generated by default as identity primary key,name text not null,description text,image_url text,published boolean not null default true,created_at timestamptz not null default now());
alter table public.fashion_categories enable row level security;
drop policy if exists public_read_fashion_categories on public.fashion_categories; create policy public_read_fashion_categories on public.fashion_categories for select to anon,authenticated using(published=true or public.is_staff());
drop policy if exists staff_manage_fashion_categories on public.fashion_categories; create policy staff_manage_fashion_categories on public.fashion_categories for all to authenticated using(public.is_staff()) with check(public.is_staff());
grant select on public.fashion_categories to anon,authenticated;
grant select,insert,update,delete on public.fashion_categories to authenticated;
